### ISSUE TITLE
Could not install Ipopt using install_ipopt.sh

### ISSUE THREAD

**Issue by atinfinity** [udacity/CarND-MPC-Project#37]
I tried to install Ipopt using `install_ipopt.sh` on Ubuntu 18.04 64bit.
But, the error occurs in `make install` process. The error message is as follows.

```
/usr/bin/install -c .libs/libcoinasl.so.1.3.6 /usr/local/lib/libcoinasl.so.1.3.6
/usr/bin/install: cannot create regular file '/usr/local/lib/libcoinasl.so.1.3.6': Permission denied
Makefile:740: recipe for target 'install-exec-local' failed
```

I checked `install_ipopt.sh`.  And, I enumerate my opinion.

- Install path is defined by `prefix=/usr/local`
- But, this script call `make install`
- I think that this script should call `sudo make install`

**Comment by mvirgo** [comment]
There's actually fairly good reasons to use `make install` instead of `sudo make install` - you can check this out in [this Stack Overflow post](https://unix.stackexchange.com/questions/20953/difference-between-make-install-and-sudo-make-install). As they mention in the post, it's preferred to use `usr/local`, which you can otherwise give yourself permission for (I believe `chmod u+w /usr/local` should work).
